version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7000:5432'
  service-1:
    depends_on:
      - database
    container_name: service-1
    build:
      context: service1
      dockerfile: Dockerfile
    image: service1:latest
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres?currentSchema=service_1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    #networks:
    #  - spring-cloud-network
  service-2:
    depends_on:
      - database
    container_name: service-2
    build:
      context: service2
      dockerfile: Dockerfile
    image: service2:latest
    ports:
      - 8082:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres?currentSchema=service_2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update